/**
 * A centralized list of supported languages for dropdowns and other UI elements.
 * The key is the language code (e.g., 'en', 'fr') and the value is the display name.
 */
export const supportedLanguages = {
	'af': 'Afrikaans',
	'bg': 'Bulgarian',
	'ca': 'Catalan',
	'cs': 'Czech',
	'cy': 'Welsh',
	'da': 'Danish',
	'de': 'German',
	'el': 'Greek',
	'en': 'English',
	'en-GB': 'English (UK)',
	'en-US': 'English (US)',
	'es': 'Spanish',
	'es-419': 'Spanish (Latin America)',
	'es-AR': 'Spanish (Argentina)',
	'es-ES': 'Spanish (Spain)',
	'es-MX': 'Spanish (Mexico)',
	'es-US': 'Spanish (US)',
	'et': 'Estonian',
	'fa': 'Persian',
	'fo': 'Faroese',
	'fr': 'French',
	'he': 'Hebrew',
	'hi': 'Hindi',
	'hr': 'Croatian',
	'hu': 'Hungarian',
	'hy': 'Armenian',
	'id': 'Indonesian',
	'it': 'Italian',
	'ja': 'Japanese',
	'ko': 'Korean',
	'lt': 'Lithuanian',
	'lv': 'Latvian',
	'nb': 'Norwegian (Bokmål)',
	'nl': 'Dutch',
	'pl': 'Polish',
	'pt-BR': 'Portuguese (Brazil)',
	'pt-PT': 'Portuguese (Portugal)',
	'ro': 'Romanian',
	'ru': 'Russian',
	'sh': 'Serbo-Croatian',
	'sk': 'Slovak',
	'sl': 'Slovenian',
	'sq': 'Albanian',
	'sr': 'Serbian',
	'sv': 'Swedish',
	'ta': 'Tamil',
	'tg': 'Tajik',
	'tr': 'Turkish',
	'uk': 'Ukrainian',
	'vi': 'Vietnamese',
};
